version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USERMAP_UID: "1000"
      USERMAP_GID: "1000"

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
        #- tika
        #- gotenberg
    ports:
      - 8010:8000
    volumes:
      - /mnt/commun/paperless/data:/usr/src/paperless/data
      - /mnt/commun/paperless/media:/usr/src/paperless/media
      - /mnt/commun/paperless/export:/usr/src/paperless/export
      - /mnt/commun/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: "1000"
      USERMAP_GID: "1000"
      PAPERLESS_CONSUMER_RECURSIVE: "true"

volumes:
  data:
  media:
  pgdata:
  redisdata:
