---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMAP=02
      - TZ=America/New_York
    volumes:
      - /home/jeremy/appdata/sonarr:/config
      - /mnt/video/series:/tv
      - /mnt/video/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
