---
version: '3'

services:
    planka:
        image: ghcr.io/plankanban/planka:latest
        command: >
            bash -c
              "for i in `seq 1 30`; do
                ./start.sh &&
                s=$$? && break || s=$$?;
                echo \"Tried $$i times. Waiting 5 seconds...\";
                sleep 5;
              done; (exit $$s)"
        restart: unless-stopped
        volumes:
            - user-avatars:/app/public/user-avatars
            - project-background-images:/app/public/project-background-images
            - attachments:/app/private/attachments
        ports:
            - 3010:1337
        environment:
            - BASE_URL=http://192.168.1.103:3010
            - DATABASE_URL=postgresql://postgres@postgres/planka
            - SECRET_KEY=${SECRET_KEY}
            - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
            - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
            - DEFAULT_ADMIN_NAME=${DEFAULT_ADMIN_NAME}
            - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME}
        depends_on:
            - postgres

    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}

volumes:
    user-avatars:
    project-background-images:
    attachments:
    db-data:
