version: "3"
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "/home/jeremy/appdata/plant-it/upload-dir:/upload-dir"
      - "/home/jeremy/appdata/plant-it/certs:/certificates"
    ports:
      - "8095:8080"
      - "4040:3000"

  db:
    image: mysql:8.0
    restart: always
    env_file: server.env
    volumes:
      - "/home/jeremy/appdata/plant-it/db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always
