---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMAP=02
      - TZ=America/New_York
      - WEBUI_PORT=8086
      - TORRENTING_PORT=6882
    volumes:
      - /home/jeremy/appdata/qbittorrent/config:/config
      - /mnt/video/downloads:/downloads
    ports:
      - 8086:8086
      - 6882:6882
      - 6882:6882/udp
    restart: unless-stopped
