---
version: "2.1"
services:
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMAP=02
      - TZ=America/New_York
    volumes:
      - /home/jeremy/appdata/radarr:/config
      - /mnt/video/data/media/movies:/movies
      - /mnt/video/data/torrents:/data
    ports:
      - 7878:7878
    restart: unless-stopped
