version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/ :latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - UMAP=02
      - TZ=America/New_York
    volumes:
      - /home/jeremy/appdata/sabnzbd:/config
      - /mnt/video/downloads:/downloads
    ports:
      - 8092:8080
    restart: unless-stopped
