version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - /home/jeremy/appdata/actual-data:/data
    restart: unless-stopped
