version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
    volumes:
      - /home/jeremy/appdata/navidrome/data:/data
      - /mnt/music:/music:ro
