---
- name: Install latest qemu-guest-agent
  hosts: all
  tasks:
      - name: Install qemu-guest-agent
        ansible.builtin.apt:
            name: qemu-guest-agent
            state: present
            update_cache: true
        become: true
