---
version: '2.1'
services:
    readarr:
        image: lscr.io/linuxserver/readarr:develop
        container_name: readarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMAP=02
            - TZ=America/New_York
        volumes:
            - /home/jeremy/appdata/readarr:/config
            - /mnt/homes/commun/Book_AudioBook:/books
            - /mnt/video/downloads:/downloads
        ports:
            - 8787:8787
        restart: unless-stopped
