---
- name: Install Docker engine and Docker Compose
  hosts: all
  become: true
  tasks:
      - name: Install dependencies
        ansible.builtin.apt:
            name:
                - ca-certificates
                - curl
                - gnupg
                - lsb-release
            state: present
            update_cache: true
        become: true

      - name: Add GPG key
        ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Add docker repository to apt
        ansible.builtin.apt_repository:
            filename: docker
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
            state: present

      - name: Install docker engine
        ansible.builtin.apt:
            name:
                - docker-ce
                - docker-ce-cli
                - containerd.io
            state: present
            update_cache: true
        become: true

      - name: Test docker
        ansible.builtin.command: docker info
        become: true
        changed_when: false

      - name: Install docker-compose
        ansible.builtin.apt:
            name:
                - docker-compose
            state: present
            update_cache: true
        become: true
