# from https://github.com/techno-tim/launchpad/blob/master/ansible/playbooks/docker.yml

- name: install latest qemu-guest-agent
  hosts: all
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
