---
version: '2.1'
services:
    deluge:
        image: linuxserver/deluge:amd64-78da80ca-ls20
        container_name: deluge
        environment:
            - PUID=1000
            - PGID=1000
            - UMAP=02
            - TZ=America/New_York
            - DELUGE_LOGLEVEL=error # optional
        volumes:
            - /home/jeremy/appdata/deluge:/config
            - /mnt/video/downloads:/downloads
        ports:
            - 8112:8112
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped
