---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMAP=02
      - TZ=America/New_York
    volumes:
      - /home/jeremy/appdata/sonarr:/config
      - /mnt/video/data/media/tv:/tv
      - /mnt/video/data/torrents:/data
    ports:
      - 8989:8989
    restart: unless-stopped
