services:
  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: SuggestArr
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /home/jeremy/appdata/suggestarr/config_files:/app/config/config_files
